defmodule AiPersonalChef.Repo.Migrations.User do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:age, :bigint, null: false)
    end

    alter table(:posts) do
      add(:date, :date, null: false)

      add(
        :author_id,
        references(:users,
          column: :id,
          name: "posts_author_id_fkey",
          type: :bigint,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:posts, "posts_author_id_fkey"))

    alter table(:posts) do
      remove(:author_id)
      remove(:date)
    end

    drop(table(:users))
  end
end
