defmodule AiPersonalChef.Repo.Migrations.Resources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
    end

    create table(:comments, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:date, :date)

      add(
        :post_id,
        references(:posts,
          column: :id,
          name: "comments_post_id_fkey",
          type: :bigint,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:comments, "comments_post_id_fkey"))

    drop(table(:comments))

    drop(table(:posts))
  end
end
