defmodule AiPersonalChef.Repo.Migrations.Hidden do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:comments) do
      add(:hidden, :boolean)
    end
  end

  def down do
    alter table(:comments) do
      remove(:hidden)
    end
  end
end
